---
# tasks for PHP role

- name: Install PHP and common extensions
  apt:
    name:
      - php
      - libapache2-mod-php
      - php-mysql
      - php-cli
      - php-curl
      - php-xml
      - php-mbstring
    state: present
    update_cache: yes

- name: Ensure Apache service is restarted to load PHP
  service:
    name: apache2
    state: restarted
